---

- fail:
    msg: "This role is supposed to be run on an ansible controller using connection: local"
  when: ansible_connection != 'local'

- fail:
    msg: "The defaults prefix contains invalid characters such as - or spaces"
  when: not match
  vars:
    match: "{{ ansible_defaults_prefix | regex_search('^[a-zA-Z0-9_]+$') }}"

- setup:
  tags:
    - deps

- name: Install python3-venv package for Debian/Ubuntu
  apt:
    name: python3-venv
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - deps

- name: Install cli dependencies
  pip:
    virtualenv_command: "{{ ansible_python_interpreter | default(discovered_interpreter_python) }} -m venv"
    requirements: "{{ role_path }}/scripts/requirements.txt"
    state: latest
    virtualenv: "{{ cli_virtualenv_path }}"
  tags:
    - deps

- name: Create directories
  file:
    path: "{{ output_role_path }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
   - vars
   - defaults
   - tasks
   - templates
   - handlers

- name: call dc_to_ansible.py
  command:
    argv: "{{ cli_argv | select() }}"
    chdir: "{{ compose_file_path | dirname }}"
  changed_when: false

- slurp:
    src: "{{ cli_output_file_path }}"
  register: cli_o

- name: Set the cli output as fact
  set_fact:
    cli_output: "{{ cli_o['content'] | b64decode | from_json }}"

- name: Render example playbook
  template:
    src: "playbook.example.yml"
    dest: "{{ output_role_path }}/playbook.example.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    trim_blocks: true
    block_start_string: '[%'
    block_end_string: '%]'
    variable_start_string: '[['
    variable_end_string: ']]'

- name: Render default and vars files and handlers
  template:
    src: "{{ item }}.yml"
    dest: "{{ output_role_path }}/{{ item }}/main.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    trim_blocks: true
    block_start_string: '[%'
    block_end_string: '%]'
    variable_start_string: '[['
    variable_end_string: ']]'
  loop:
    - vars
    - defaults
    - handlers

- name: Copy compose config content
  copy:
    content: "{{ cli_output['final_compose'] | to_nice_yaml(sort_keys=False, indent=2) }}"
    dest: "{{ output_role_path }}/templates/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Render task files
  template:
    src: "tasks/{{ item }}"
    dest: "{{ output_role_path }}/tasks/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    trim_blocks: true
    block_start_string: '[%'
    block_end_string: '%]'
    variable_start_string: '[['
    variable_end_string: ']]'
  loop:
   - install.yml
   - main.yml
   - remove.yml
   - run_cmds.yml

- name: Create molecule directories
  file:
    path: "{{ output_role_path }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
   - molecule
   - molecule/default
  when: molecule_docker_test

- name: Copy molecule test files
  template:
    src: "molecule/default/{{ item }}"
    dest: "{{ output_role_path }}/molecule/default/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    trim_blocks: true
    block_start_string: '[%'
    block_end_string: '%]'
    variable_start_string: '[['
    variable_end_string: ']]'
  loop:
    - converge.yml
    - molecule.yml
  when: molecule_docker_test

- name: Render README.md
  template:
    src: README.md
    dest: "{{ output_role_path }}/README.md"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Remove cli json output
  file:
    path: "{{ cli_output_file_path }}"
    state: absent
  when: remove_cli_artefact
