---
- hosts: localhost
  vars:
[% for d in cli_output['defaults'] %]
[% if d['is_secret'] %]
    [[ d.key ]]: "[[ d['secret_expr'] ]]"
[% else %]
[% if d.value is mapping %]
    [[ d.key ]]:
[% for k, v in d.value.items() %]
      [[ k ]]: "[[ v ]]"
[% endfor %]
[% else %]
    [[ d.key ]]: [[ d['value'] ]]
[% endif %]
[% endif %]
[% endfor %]