---

- name: ensure deployment user for [[ cli_output['role_name'] ]]
  user:
    name: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    state: "{{ [[ cli_output['defaults_prefix'] ]]state | default('present') }}"
    create_home: true
    uid: "{{ [[ cli_output['defaults_prefix'] ]]user_id }}"
    shell: /bin/bash

- name: Ensure user is added to the docker group.
  user:
    name: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    groups: docker
    append: true

# Issues with docker python package >=7.0.0
# https://github.com/docker/docker-py/releases/tag/7.0.0
# https://github.com/docker/docker-py/issues/3194
- name: legacy | Ensure docker python packages compose v1
  pip:
    name:
      - docker==6.1.3
      - docker-compose
  become: true
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  when: compose_v1

- name: Install Docker dependencies for modules
  apt:
    name:
      - python3-docker
      - python3-requests
    update_cache: true
  become: true
  when: not compose_v1

# Read this blogpost: https://forum.ansible.com/t/breaking-changes-with-pip-and-system-packages/2177
- name: Overwrite the ansible_python_interpreter
  set_fact:
    ansible_python_interpreter: "{{ docker_utils_venv_path }}/bin/python"

- name: Ensure repository paths are present
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  loop:
   - "{{ repository_src }}"
   - "{{ repository_src }}/scripts"

- name: ensure external network exists
  community.docker.docker_network:
    name: "{{ [[ cli_output['defaults_prefix'] ]]ext_net }}"
    driver: bridge
    attachable: true
    state: present

- name: Check if docker-compose.yml exists
  stat:
    path: "{{ repository_src }}/docker-compose.yml"
  register: compose

- name: test docker-compose changed
  template:
    src: "docker-compose.yml"
    dest: "{{ repository_src }}/docker-compose.yml"
    owner: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    mode: "600"
  check_mode: true
  register: repo_copy_test
  when: not compose.stat.exists

- name: legacy | Stop services since compose has changed
  community.docker.docker_compose:
    project_name: "{{ [[ cli_output['defaults_prefix'] ]]project_name }}"
    project_src: "{{ repository_src }}"
    state: absent
    files:
[% for f in cli_output['compose_files'] %]
      - [[ f | basename ]]
[% endfor %]
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  when:
  - compose_v1
  - not [[ cli_output['defaults_prefix'] ]]remove
  - compose.stat.exists
  - repo_copy_test.changed

- name: Stop services since compose has changed
  community.docker.docker_compose_v2:
    project_name: "{{ [[ cli_output['defaults_prefix'] ]]project_name }}"
    project_src: "{{ repository_src }}"
    state: absent
    files:
[% for f in cli_output['compose_files'] %]
      - [[ f | basename ]]
[% endfor %]
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  when:
  - not compose_v1
  - not [[ cli_output['defaults_prefix'] ]]remove
  - compose.stat.exists
  - repo_copy_test.changed

- name: Copy docker-compose.yml
  template:
    src: "docker-compose.yml"
    dest: "{{ repository_src }}/docker-compose.yml"
    owner: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    mode: "600"
  register: repo_copy

- name: Run pre-start commands
  command: "{{ item }}"
  loop: "{{ [[ cli_output['defaults_prefix'] ]]pre_startup_commands }}"
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"

- name: legacy | Ensure services are {{ [[ cli_output['defaults_prefix'] ]]state }}
  community.docker.docker_compose:
    project_name: "{{ [[ cli_output['defaults_prefix'] ]]project_name }}"
    project_src: "{{ repository_src }}"
    debug: true
    state: "{{ [[ cli_output['defaults_prefix'] ]]state }}"
    build: false
    files:
[% for f in cli_output['compose_files'] %]
      - [[ f | basename ]]
[% endfor %]
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  when:
    - compose_v1
    - not [[ cli_output['defaults_prefix'] ]]remove

# Requires community.docker >= 3.8.0. ansible-galaxy does not handle collection dependencies in roles meta/main.yml
- name: Ensure services are {{ [[ cli_output['defaults_prefix'] ]]state }}
  community.docker.docker_compose_v2:
    project_name: "{{ [[ cli_output['defaults_prefix'] ]]project_name }}"
    project_src: "{{ repository_src }}"
    state: "{{ [[ cli_output['defaults_prefix'] ]]state }}"
    build: never
    files:
[% for f in cli_output['compose_files'] %]
      - [[ f | basename ]]
[% endfor %]
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  when:
    - not compose_v1
    - not [[ cli_output['defaults_prefix'] ]]remove

- name: Run post-shutdown commands
  command: "{{ item }}"
  loop: "{{ [[ cli_output['defaults_prefix'] ]]post_shutdown_commands }}"
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"

- name: Put auto-update script
  copy:
    content: |
      #!/usr/bin/env bash
      
      set - eu
      cd {{ repository_src }}
      docker compose pull
      docker compose up -d

    dest: "{{ repository_src }}/autoupdate.sh"
    owner: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    mode: "770"
  when: [[ cli_output['defaults_prefix'] ]]auto_update

- name: Set auto-update cron to {{ cron_state }}
  cron:
    name: update all services for [[ cli_output['role_name'] ]]
    job: "{{ repository_src }}/autoupdate.sh"
    hour: "{{ [[ cli_output['defaults_prefix'] ]]auto_update_cron_hour }}"
    minute: "{{ [[ cli_output['defaults_prefix'] ]]auto_update_cron_minute }}"
    weekday: "{{ [[ cli_output['defaults_prefix'] ]]auto_update_cron_weekday }}"
    month: "{{ [[ cli_output['defaults_prefix'] ]]auto_update_cron_month }}"
    user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
    state: "{{ cron_state }}"
  become_user: "{{ [[ cli_output['defaults_prefix'] ]]user }}"
  vars:
    cron_state: "{{ 'present' if [[ cli_output['defaults_prefix'] ]]auto_update else 'absent' }}"
